import type { Institution } from "@/pages/user/discover/types";

export const discoverInstitutions: Institution[] = [
  {
    id: 1,
    name: "St. Marys Cathedral",
    faith: "Christianity",
    denomination: "Catholic",
    language: "English",
    distanceKm: 2.4,
    verified: true,
    sponsored: false,
    nearNow: true,
    serviceTime: "Service live now - 6:00 PM",
    mapX: "22%",
    mapY: "35%",
    location: "Kampala Central",
    followers: "18.2k followers",
  },
  {
    id: 2,
    name: "Al Noor Community Centre",
    faith: "Islam",
    denomination: "Muslim Community",
    language: "Arabic",
    distanceKm: 4.8,
    verified: true,
    sponsored: false,
    nearNow: true,
    serviceTime: "Reflection starts in 18 min",
    mapX: "62%",
    mapY: "44%",
    location: "Bugolobi",
    followers: "9.4k followers",
  },
  {
    id: 3,
    name: "FaithHub Global Chapel",
    faith: "Christianity",
    denomination: "Pentecostal",
    language: "English",
    distanceKm: 6.1,
    verified: true,
    sponsored: true,
    nearNow: false,
    serviceTime: "Series starts tomorrow - 7:30 PM",
    mapX: "48%",
    mapY: "66%",
    location: "Ntinda",
    followers: "24.1k followers",
  },
  {
    id: 4,
    name: "Beth Shalom Fellowship",
    faith: "Judaism",
    denomination: "Undisclosed",
    language: "English",
    distanceKm: 8.7,
    verified: false,
    sponsored: false,
    nearNow: false,
    serviceTime: "Sabbath gathering - Friday 6:15 PM",
    mapX: "74%",
    mapY: "24%",
    location: "Kololo",
    followers: "3.2k followers",
  },
  {
    id: 5,
    name: "Kingdom Youth Movement",
    faith: "Christianity",
    denomination: "Interfaith",
    language: "English",
    distanceKm: 3.6,
    verified: true,
    sponsored: false,
    nearNow: true,
    serviceTime: "Youth worship tonight - 8:00 PM",
    mapX: "32%",
    mapY: "58%",
    location: "Muyenga",
    followers: "11.8k followers",
  },
];
