type RouteParam = string | number;

function encodeSegment(value: RouteParam) {
  return encodeURIComponent(String(value).trim());
}

export const routes = {
  public: {
    landing: "/",
    access: "/access",
    shellPreview: "/shell-preview",
  },
  app: {
    root: "/app",
    shell: "/app-shell",
    user: {
      base: "/app/user",
      entry: "/app/user/entry",
      auth: "/app/user/auth",
      profile: "/app/user/profile",
      home: "/app/user/home",
      community: "/app/user/community",
      noticeboard: "/app/user/noticeboard",
      discover: "/app/user/discover",
      institution: "/app/user/institution",
      institutionPattern: "/app/user/institution/:institutionId",
      institutionById: (institutionId: RouteParam) =>
        `/app/user/institution/${encodeSegment(institutionId)}`,
      series: "/app/user/series",
      seriesDetail: "/app/user/series/detail",
      seriesDetailPattern: "/app/user/series/:seriesId",
      seriesDetailById: (seriesId: RouteParam) => `/app/user/series/${encodeSegment(seriesId)}`,
      episode: "/app/user/episode",
      episodePattern: "/app/user/episode/:episodeId",
      episodeById: (episodeId: RouteParam) => `/app/user/episode/${encodeSegment(episodeId)}`,
      replay: "/app/user/replay",
      replayPattern: "/app/user/replay/:replayId",
      replayById: (replayId: RouteParam) => `/app/user/replay/${encodeSegment(replayId)}`,
      clips: "/app/user/clips",
      liveHub: "/app/user/live",
      liveWaitingRoom: "/app/user/live/waiting-room",
      livePlayer: "/app/user/live/player",
      livePlayerPattern: "/app/user/live/:sessionId/player",
      livePlayerBySession: (sessionId: RouteParam) =>
        `/app/user/live/${encodeSegment(sessionId)}/player`,
      liveChat: "/app/user/live/chat",
      liveChatPattern: "/app/user/live/:sessionId/chat",
      liveChatBySession: (sessionId: RouteParam) =>
        `/app/user/live/${encodeSegment(sessionId)}/chat`,
      events: "/app/user/events",
      eventDetail: "/app/user/events/detail",
      eventDetailPattern: "/app/user/events/:eventId",
      eventDetailById: (eventId: RouteParam) => `/app/user/events/${encodeSegment(eventId)}`,
      giving: "/app/user/giving",
      wallet: "/app/user/wallet",
      fundDetail: "/app/user/fund",
      fundDetailPattern: "/app/user/fund/:slug",
      fundDetailBySlug: (slug: RouteParam) => `/app/user/fund/${encodeSegment(slug)}`,
      fundDetailById: (fundId: RouteParam) => `/app/user/fund/${encodeSegment(fundId)}`,
      membership: "/app/user/membership",
      reviews: "/app/user/reviews",
      settings: "/app/user/settings",
      qa: "/app/user/qa",
      resources: "/app/user/resources",
      resourceDetail: "/app/user/resources/detail",
      resourceDetailPattern: "/app/user/resources/:resourceId",
      resourceDetailById: (resourceId: RouteParam) =>
        `/app/user/resources/${encodeSegment(resourceId)}`,
      counseling: "/app/user/counseling",
      counselingProfile: "/app/user/counseling/profile",
      counselingProfilePattern: "/app/user/counseling/:counselorId",
      counselingProfileById: (counselorId: RouteParam) =>
        `/app/user/counseling/${encodeSegment(counselorId)}`,
      counselingBook: "/app/user/counseling/book",
      counselingSession: "/app/user/counseling/session",
      counselingSessionPattern: "/app/user/counseling/session/:sessionId",
      counselingSessionById: (sessionId: RouteParam) =>
        `/app/user/counseling/session/${encodeSegment(sessionId)}`,
      counselingHistory: "/app/user/counseling/history",
    },
    provider: {
      base: "/app/provider",
      onboarding: "/app/provider/onboarding",
      dashboard: "/app/provider/dashboard",
      seriesBuilder: "/app/provider/series-builder",
      episodeBuilder: "/app/provider/episode-builder",
      postLive: "/app/provider/post-live",
      liveBuilder: "/app/provider/live-builder",
      liveSchedule: "/app/provider/live-schedule",
      liveOps: "/app/provider/live-ops",
      liveStudio: "/app/provider/live-studio",
      streamToPlatforms: "/app/provider/stream-to-platforms",
      notifications: "/app/provider/notifications",
      contacts: "/app/provider/contacts",
      resources: "/app/provider/resources",
      noticeboard: "/app/provider/noticeboard",
      resourceDetail: "/app/provider/resources/detail",
      resourceDetailPattern: "/app/provider/resources/:resourceId",
      resourceDetailById: (resourceId: RouteParam) =>
        `/app/provider/resources/${encodeSegment(resourceId)}`,
      community: "/app/provider/community",
      events: "/app/provider/events",
      funds: "/app/provider/funds",
      fundCreate: "/app/provider/funds/create",
      fundDetail: "/app/provider/fund",
      fundDetailPattern: "/app/provider/fund/:slug",
      fundDetailBySlug: (slug: RouteParam) => `/app/provider/fund/${encodeSegment(slug)}`,
      fundDetailById: (fundId: RouteParam) => `/app/provider/fund/${encodeSegment(fundId)}`,
      wallet: "/app/provider/wallet",
      reviewsModeration: "/app/provider/reviews-moderation",
      counseling: "/app/provider/counseling",
      qa: "/app/provider/qa",
    },
    admin: {
      base: "/app/admin",
      overview: "/app/admin/overview",
      verification: "/app/admin/verification",
      liveModeration: "/app/admin/live-moderation",
      policy: "/app/admin/policy",
      finance: "/app/admin/finance",
      channels: "/app/admin/channels",
      security: "/app/admin/security",
      counseling: "/app/admin/counseling",
      noticeboard: "/app/admin/noticeboard",
      qa: "/app/admin/qa",
    },
  },
  aliases: {
    user: "/user",
    provider: "/provider",
    admin: "/admin",
  },
  enterprise: {
    superAdminOverview: "/super-admin/overview",
    tenantAdminOverview: "/tenant-admin/overview",
    opsIncidents: "/ops/incidents",
  },
} as const;

export const faithHubRouteAliases: Record<string, string[]> = {
  [routes.app.user.institution]: [routes.app.user.institutionPattern],
  [routes.app.user.seriesDetail]: [routes.app.user.seriesDetailPattern],
  [routes.app.user.episode]: [routes.app.user.episodePattern],
  [routes.app.user.replay]: [routes.app.user.replayPattern],
  [routes.app.user.livePlayer]: [routes.app.user.livePlayerPattern],
  [routes.app.user.liveChat]: [routes.app.user.liveChatPattern],
  [routes.app.user.eventDetail]: [routes.app.user.eventDetailPattern],
  [routes.app.user.fundDetail]: [routes.app.user.fundDetailPattern],
  [routes.app.user.resourceDetail]: [routes.app.user.resourceDetailPattern],
  [routes.app.provider.resourceDetail]: [routes.app.provider.resourceDetailPattern],
  [routes.app.provider.fundDetail]: [routes.app.provider.fundDetailPattern],
  [routes.app.user.counselingProfile]: [routes.app.user.counselingProfilePattern],
  [routes.app.user.counselingSession]: [routes.app.user.counselingSessionPattern],
};
