import {
  Activity,
  BadgeCheck,
  Building2,
  DollarSign,
  Flag,
  LayoutDashboard,
  ReceiptText,
  Settings2,
  ShieldAlert,
  Users,
} from "lucide-react";
import type { EnterpriseNavItem } from "@/types/enterprise";

export const superAdminNav: EnterpriseNavItem[] = [
  {
    id: "sa-overview",
    label: "Overview",
    route: "/super-admin/overview",
    icon: LayoutDashboard,
    permission: "view_platform_analytics",
  },
  {
    id: "sa-tenants",
    label: "Tenants",
    route: "/super-admin/tenants",
    icon: Building2,
    permission: "manage_tenants",
  },
  {
    id: "sa-providers",
    label: "Providers",
    route: "/super-admin/providers",
    icon: BadgeCheck,
    permission: "manage_providers",
  },
  {
    id: "sa-users",
    label: "Users",
    route: "/super-admin/users",
    icon: Users,
    permission: "manage_users",
  },
  {
    id: "sa-incidents",
    label: "Incidents",
    route: "/super-admin/incidents",
    icon: ShieldAlert,
    permission: "manage_incidents",
    badge: "high",
  },
  {
    id: "sa-verification",
    label: "Verification",
    route: "/super-admin/verification",
    icon: BadgeCheck,
    permission: "manage_verification",
  },
  {
    id: "sa-billing",
    label: "Billing",
    route: "/super-admin/billing",
    icon: DollarSign,
    permission: "view_billing",
  },
  {
    id: "sa-audit",
    label: "Audit Logs",
    route: "/super-admin/audit-logs",
    icon: ReceiptText,
    permission: "view_audit_logs",
  },
  {
    id: "sa-feature-flags",
    label: "Feature Flags",
    route: "/super-admin/feature-flags",
    icon: Flag,
    permission: "manage_feature_flags",
  },
  {
    id: "sa-settings",
    label: "Settings",
    route: "/super-admin/settings",
    icon: Settings2,
    permission: "manage_settings",
  },
  {
    id: "sa-health",
    label: "System Health",
    route: "/super-admin/system-health",
    icon: Activity,
    permission: "view_platform_analytics",
  },
];
